builds:
  - binary: ssrfuzz
    goos:
      - linux
      - freebsd
      - openbsd
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ignore:
      - goos: 
          freebsd
        goarch: arm64

archives:
  - id: tgz
    format: tar.gz
    replacements:
        darwin: macOS

signs:
  - artifacts: checksum
